### PR TITLE
Migrated to Swift 4.2 (using autofix)

### PR DESCRIPTION
**Pull request by Anarchoschnitzel**

### CODE REVIEW

**Comment by loregr** [comment]
@Anarchoschnitzel thanks for your PR, really appreciated. But it seems that CI is failing, I'll merge it once that CI goes green. Thanks

**Comment by Anarchoschnitzel** [comment]
Is the CI configured to build with Xcode 10 and Swift 4.2?

**Comment by Anarchoschnitzel** [comment]
Okay I updated the .swift-version to 4.2 and adjusted the .travis.yml to use Xcode 10 and iOS 12.
Would be great if you could have a short look over these changes as I am not that much experienced with travis CI.
However the build is green now. Thanks :)

**Comment by loregr** [comment]
@Anarchoschnitzel great, thanks a lot for your contribution :)

**Pull request merged**
