### PR TITLE
- Delete .py from resources

### PR DESCRIPTION
**Pull request by inft**
[18:55:52]: [Transporter Error Output]: ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [iOS.app/Frameworks/LGButton.framework/GetTTFFontName.py] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

### CODE REVIEW

**Comment by loregr** [comment]
This PR is just moving the .py file to a different folder. I don't see any good reason to merge it since that file is not actually linked to any resource. I was considering removing .py files, but then I thought that they may be useful for future updates of the font icons, so I kept them there. Also, the reported issue looks more like a local issue on your project. Library Pod and Example app don't have that dependency. You can check it by downloading/cloning this repo from scratch. If I'm missing something, please add a comment here. Thanks.

**Comment by inft** [comment]
because, `LGButton/LGButton.podspec`, `s.resources = "LGButton/Resources/*"`
but, the .py file is't a resource,  
and i delete the .py file from resources, it's success
or, please delete the .py from resources, 
thank you very much

**Comment by inft** [comment]
I use fastlane upload the .ipa to testflight
```ruby
    gym(
      scheme: "iOSPro",
      export_xcargs: "-allowProvisioningUpdates",
      output_directory: "./output",
      export_method:'app-store',
      configuration: 'Release'
    ) 
    pilot(
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      team_id: "118739734",
      ipa: "./output/iOS.ipa",
      app_identifier: "cc.xx.iOS"
    )
```

**Comment by loregr** [comment]
I see your point now, thanks for the clarification.

**Pull request merged**
